# Welcome to Jekyll!
# _config.yml is where you can configure site-wide settings.

title: Mohsen's Tech Blog
description: Personal blog about tech, programming, and learnings
theme: minima
author: Mohsen Niksirat
email: mohsen@example.com

# GitHub is happy to use this for GitHub Pages
github_metadata:
  repository: mohsen-niksirat/mohsen-niksirat.github.io

# Enable the site-wide license
show_donations: false

# Social links
social_links:
  - url: https://github.com/mohsen-niksirat
    icon: github
  - url: https://twitter.com/mohsenniksirat
    icon: twitter
  - url: https://www.linkedin.com/in/mohsen-niksirat
    icon: linkedin

# Pagination
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions

permalink: /:year/:month/:day/:title/
timezone: Asia/Tehran

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/