# Welcome to Jekyll!

title: Mohsen's Tech Blog
description: Personal blog about tech, programming, and learnings
author: Mohsen Niksirat
email: mohsen@example.com
url: https://mohsen-niksirat.github.io/mohsen-tech-blog
baseurl: /mohsen-tech-blog

# SEO plugins (GitHub Pages provides these automatically)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/
timezone: Asia/Tehran

markdown: kramdown